[package]
name = "chatmessagediscordclone"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.27"
futures-util = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.36", features = ["macros", "rt-multi-thread", "sync", "net", "time"] }
tokio-tungstenite = { version = "0.21", features = ["rustls-tls-webpki-roots"] }
argon2 = "0.5"
chrono = { version = "0.4", features = ["serde", "clock"] }
rand = "0.8"
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres", "chrono", "uuid"] }
uuid = { version = "1.7", features = ["v4", "serde"] }

[package.metadata.bundle]
name = "BlastFromThePast"
identifier = "com.blastfromthepast"
category = "public.app-category.social-networking"
