[build]
builder = "nixpacks"
buildCommand = "cargo build --release --bin server --features server"

[deploy]
startCommand = "./target/release/server"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[services]]
name = "messenger-server"
