name: Deploy Web Version

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: .
          cache-targets: "true"

      - name: Install Trunk
        run: cargo install --locked trunk

      - name: Install wasm-opt
        run: cargo install wasm-opt --locked

      - name: Build Web
        run: trunk build --release --public-url /blast-from-the-past-messenger/ -- --features client

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
